packages/core/package-lock.json, packages/core/package.json, packages/core/src/components/Container/Container.tsx, packages/core/src/components/Entity/Entity.module.css, packages/core/src/components/Entity/Entity.tsx, packages/core/src/components/Entity/EntityField.tsx, packages/core/src/components/Entity/EntityThumbnail.tsx, packages/core/src/components/Entity/dots-menu.module.css, packages/core/src/components/Entity/index.tsx, packages/core/src/components/Menu/Menu.tsx, packages/core/src/components/Skeleton/Skeleton.tsx, packages/core/src/components/Skeleton/skeleton.module.css, packages/core/src/icons/FacebookIcon.tsx, packages/core/src/icons/GitHub.tsx, packages/core/src/icons/GoogleIcon.tsx, packages/core/src/icons/MoreVertical.tsx, packages/core/src/icons/index.ts, packages/core/src/index.ts, packages/docs/components/DesignLayout/DesignLayout.tsx, packages/docs/components/DesignLayout/DesignLayoutInner.tsx, packages/docs/package-lock.json, packages/docs/package.json, packages/docs/pages/design/entity.mdx
- fix(Container): prop logic
- feat: update Entity, Container, Skeleton
=> Entity, Container, Skeleton

packages/core/package.json, packages/core/src/icons/MinusIcon.tsx, packages/core/src/icons/PlusIcon.tsx
- fix(Icons): use relative import
- chore(core): script updates
- chore(core): `0.1.0-rc52`
=> fix icon imports

packages/core/package.json, packages/core/src/components/KeyboardInput/index.tsx, packages/core/src/components/KeyboardInput/kbd.module.css, packages/core/src/components/KeyboardInput/kbd.tsx, packages/core/src/index.ts
Closes https://github.com/nextjs-components/nextjs-components/issues/15
=> feat: add KeyboardInput

packages/core/package-lock.json, packages/core/package.json, packages/core/src/components/Capacity/Capacity.tsx, packages/core/src/components/Capacity/capacity.module.css, packages/core/src/components/Capacity/index.tsx, packages/core/src/index.ts
=> feat: `Capacity`

packages/core/package.json, packages/core/src/components/status-dot/index.tsx, packages/core/src/components/status-dot/status-dot.module.css, packages/core/src/components/status-dot/status-dot.tsx, packages/core/src/index.ts, packages/docs/components/DesignLayout/DesignLayoutInner.tsx, packages/docs/package-lock.json, packages/docs/pages/design/status-dot.mdx
=> feat: `StatusDot`; `0.1.0-rc56`

packages/core/src/components/Modal/Modal.test.tsx, packages/core/src/components/Modal/Modal.tsx, packages/docs/components/DesignLayout/DesignLayoutInner.tsx, packages/docs/package-lock.json, packages/docs/pages/design/modal.mdx
=> fix(`Modal`): scroll lock

packages/core/package-lock.json, packages/core/package.json
- `npm version prerelease --preid=rc`
=> chore(core): version `0.1.0-rc.71`

packages/core/src/components/Snippet/Snippet.module.css, packages/core/src/components/Snippet/Snippet.tsx, packages/docs/components/DesignLayout/DesignLayoutInner.tsx, packages/docs/pages/design/snippet.mdx
Closes https://github.com/nextjs-components/nextjs-components/issues/55
=> feat(Snippet): dim on tab focus

packages/core/src/components/Input/TextField.tsx
closes https://github.com/nextjs-components/nextjs-components/issues/78
=> feat(TextField): accept ref

.github/release.yml, .github/workflows/publish.yaml
- feat: `release.yml`
- chore: add label to auto-gen PR
=> feat: `release.yml`

packages/core/src/components/Select/ModeSelect.tsx, packages/core/src/components/Select/Select.module.css, packages/core/src/components/Select/Select.test.tsx, packages/core/src/components/Select/Select.tsx, packages/core/src/components/ShowMore/ShowMore.tsx, packages/core/src/components/ShowMore/index.tsx, packages/docs/components/DesignLayout/DesignLayout.tsx, packages/docs/components/DesignLayout/DesignLayoutInner.tsx, packages/docs/components/DesignLayout/design.module.css, packages/docs/pages/design/show-more.mdx
- feat: `ShowMore`
- chore: refactor `Select` - add `useId` - remove hover style
- chore(docs): add `show-more` - replace ModeSelect
closes https://github.com/nextjs-components/nextjs-components/issues/20
=> feat: add `ShowMore`; refactor `Select`

package-lock.json, packages/core/package.json, packages/core/src/components/Button/Button.tsx, packages/core/src/components/Collapse/Collapse.tsx, packages/core/src/components/Details/Details.tsx, packages/core/src/components/Details/details.module.css, packages/core/src/components/Drawer/Drawer.tsx, packages/core/src/components/Menu/Menu.tsx, packages/core/src/components/Menu/menu-item.tsx, packages/core/src/components/Modal/Modal.tsx, packages/core/src/components/Radio/Radio.tsx, packages/core/src/components/Select/ModeSelect.tsx, packages/core/src/components/Select/Select.tsx, packages/core/src/components/Snippet/Snippet.tsx, packages/core/src/components/Toast/ToastArea.test.tsx, packages/core/src/components/Toast/ToastArea.tsx, packages/core/src/components/Toggle/Toggle.tsx, packages/docs/layouts/DesignLayout/DesignLayoutInner.tsx, packages/docs/pages/docs/radio.mdx
- chore: `@react-aria/stately` → `react-aria/stately
- update imports
- refactor `Details`
- improve `Radio`; add docs
=> use `react-aria`; refactor `Details`; improve `Radio`

package-lock.json, packages/core/package.json, packages/core/src/components/Button/Button.tsx, packages/core/src/components/Menu/Menu.module.css, packages/core/src/components/Menu/Menu.tsx, packages/core/src/components/Menu/menu-context.tsx, packages/core/src/components/Menu/menu-item.tsx
- progress
- update styles
- core: remove react-popper @popperjs/core
=> menu updates; remove deps

packages/core/src/components/tabs/tabs.tsx
=> bugfix(Tabs): disabled is still interactive

packages/core/src/components/Scroller/Scroller.tsx, packages/core/src/components/combobox/combobox.tsx
- core(Combobox): Input `loading` & type fixes
- core(Scroller): remove `lodash/clamp`
=> Combobox: `loading` style & type fixes

package-lock.json, packages/core/package.json, packages/core/src/components/combobox/combobox.tsx, packages/docs/package.json
closes https://github.com/nextjs-components/nextjs-components/issues/165
=> fix combobox input classname

packages/core/src/components/Button/button.module.css, packages/core/src/components/Note/Note.module.css, packages/core/src/components/Note/Note.tsx, packages/core/src/styles/globals.css, packages/docs/app/design/(components)/[slug]/note.mdx, packages/docs/app/design/(components)/[slug]/page.tsx, packages/docs/app/design/(components)/nodes.json
This is a `major` version (breaking) change to the `Note` component's API
This is a `patch` (style-only) change to the `Button` component
=> core: Update `Note`

packages/core/src/components/Note/Note.tsx
=> Note: add missing spans

packages/core/src/components/Badge/Badge.module.css, packages/core/src/components/Badge/Badge.tsx, packages/core/src/components/Table/Table.tsx, packages/docs/app/design/(components)/[slug]/badge.mdx, packages/docs/app/design/(components)/[slug]/renderer.tsx
This continues work from https://github.com/nextjs-components/nextjs-components/pull/170
=> core(Badge): API updates

packages/core/src/components/tabs/tabs.module.css
**This pull request makes the following changes:**
Fixes issue #212
=> bugfix (Tabs): disabled state shows cursor as pointer on hover
